LOCAL_DATA_DIR: /home/cedric/projet/NetCDF_STREAMING/netcdf-streaming/test_perfo/data/
RESULT_FILE: performance_acces_lighttpd_PIXC_s_off.txt
NETCDF_TEST: True
NETCDF_FILE: SWOT_L2_HR_PIXC_509_011_242R_20230503T014506_20230503T014517_PIA1_01_s_off.nc
XARRAY_TEST: True
H5PY_TEST: True
CHUNKINDEX_TEST: True
ZARR_TEST: True
ZARR_FILE: SWOT_L2_HR_PIXC_509_011_242R_20230503T014506_20230503T014517_PIA1_01.zarr
NCZARR_TEST: True
NCZARR_FILE: SWOT_L2_HR_PIXC_509_011_242R_20230503T014506_20230503T014517_PIA1_01.nczarr
SLICE_DATA: (slice(6000, 8001),slice(0, 1))
VARIABLE: pixel_cloud/interferogram
LIGHTTPD_CONFIG: http://127.0.0.1:9445
NUM_ITER: 10

TECHNO: lighttpd
