LOCAL_DATA_DIR: /home/cedric/projet/NetCDF_STREAMING/netcdf-streaming/test_perfo/data/
RESULT_FILE: performance_acces_lighttpd_fusion_s_off_pixel_drilling.txt
NETCDF_TEST: True
NETCDF_FILE: fusion_s_off.nc
XARRAY_TEST: True
H5PY_TEST: True
CHUNKINDEX_TEST: True
ZARR_TEST: True
ZARR_FILE: fusion.zarr
NCZARR_TEST: True
NCZARR_FILE: fusion.nczarr
SLICE_DATA: (slice(0,72),slice(280, 281),slice(506,507))
VARIABLE: uo
LIGHTTPD_CONFIG: http://127.0.0.1:9445
NUM_ITER: 10
TECHNO: S3
ENDPOINT_URL: https://s3.datalake.cnes.fr
BUCKET_NAME: 
