LOCAL_DATA_DIR: /home/cedric/projet/NetCDF_STREAMING/netcdf-streaming/test_perfo/data/
RESULT_FILE: performance_acces_lighttpd_PRECALSSH_s_on.txt
NETCDF_TEST: True
NETCDF_FILE: SWOT_L2_LR_PreCalSSH_Expert_002_086_20230814T031152_20230814T040129_PIA1_01_s_on.nc
XARRAY_TEST: True
H5PY_TEST: True
CHUNKINDEX_TEST: True
ZARR_TEST: True
ZARR_FILE: SWOT_L2_LR_PreCalSSH_Expert_002_086_20230814T031152_20230814T040129_PIA1_01.zarr
NCZARR_TEST: True
NCZARR_FILE: SWOT_L2_LR_PreCalSSH_Expert_002_086_20230814T031152_20230814T040129_PIA1_01.nczarr
SLICE_DATA: (slice(6000, 8001),slice(0, 69))
VARIABLE: ssh_karin
LIGHTTPD_CONFIG: http://127.0.0.1:9445
NUM_ITER: 10

TECHNO: lighttpd
