RESULT_DIR: /home/cedric/projet/NetCDF_STREAMING/netcdf-streaming/PERFO/lighttpd/plot/data/
OUTPUT_DIR: /home/cedric/projet/NetCDF_STREAMING/netcdf-streaming/PERFO/lighttpd/plot/
DATA_SHUFFLE_ON: performance_acces_lighttpd_fusion_s_on_spatial_frame.txt
DATA_SHUFFLE_OFF: performance_acces_lighttpd_fusion_s_off_spatial_frame.txt
FIGURE_NAME: test_figure_direct_fusion_spatial_frame.png
FIGURE_TITLE: Read time by method on local posix server
NETCDF4_DATASET: True
NETCDF4_DATASET_NAME: NetCDF4_dataset
NETCDF4_H5PY: True 
NETCDF4_H5PY_NAME: NetCDF4_h5py
NETCDF4_FSSPEC_H5PY: False
NETCDF4_FSSPEC_H5PY_NAME: NetCDF4_h5py_fsspec
NETCDF4_XARRAY: True 
NETCDF4_XARRAY_NAME: NetCDF4_xarray
NETCDF4_FSSPEC_XARRAY: False
NETCDF4_FSSPEC_XARRAY_NAME: NetCDF4_xarray_fsspec
CHUNKINDEX_FSSPEC_LOCAL: False
CHUNKINDEX_FSSPEC_LOCAL_NAME: chunkindex_fsspec_local
CHUNKINDEX_FSSPEC_REMOTE: False 
CHUNKINDEX_FSSPEC_REMOTE_NAME: chunkindex_fsspec
CHUNKINDEX_LOCAL: False
CHUNKINDEX_LOCAL_NAME: chunkindex_local
CHUNKINDEX_REMOTE: True 
CHUNKINDEX_REMOTE_NAME: chunkindex
ZARR_FSSPEC: False 
ZARR_FSSPEC_NAME: zarr_fsspec
ZARR_FSSPEC_XARRAY: False
ZARR_FSSPEC_XARRAY_NAME: zarr_xarray_fsspec
ZARR: True 
ZARR_NAME: zarr
ZARR_XARRAY: True 
ZARR_XARRAY_NAME: zarr_xarray
NCZARR_DATASET: True 
NCZARR_DATASET_NAME: nczarr_dataset
NCZARR_FSSPEC_ZARR: False
NCZARR_FSSPEC_ZARR_NAME: nczarr_zarr_fsspec
NCZARR_FSSPEC_XARRAY: False
NCZARR_FSSPEC_XARRAY_NAME: nczarr_xarray_fsspec
NCZARR_ZARR: True
NCZARR_ZARR_NAME: nczarr_zarr
NCZARR_XARRAY: True
NCZARR_XARRAY_NAME: nczarr_xarray
