name: netcdf-streaming-env
dependancies:
 - python=3.10
 - numpy=2.1.2
 - h5py=3.12.1
 - xarray=2024.9.0
 - netCDF4=1.7.2
 - fsspec=2024.9.0
 - s3fs=2024.9.0
 - zarr=2.18.3
 - certifi=2024.8.30
 - h5py=3.12.1
 - Cython=3.0.11
 - h5netcdf=1.4.0
 - boto3=1.35.23
 
